# Generated by Django 5.1 on 2024-09-27 07:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_member_delete_userprofile'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=100)),
                ('gender', models.CharField(max_length=10)),
                ('father_name', models.CharField(max_length=100)),
                ('grandfather_name', models.CharField(max_length=100)),
                ('permanent_address', models.CharField(max_length=255)),
                ('temporary_address', models.CharField(max_length=255)),
                ('date_of_birth', models.DateField()),
                ('phone_number', models.CharField(max_length=15)),
                ('email', models.EmailField(max_length=254)),
                ('blood_group', models.CharField(max_length=10)),
                ('terms_agreed', models.BooleanField(default=False)),
            ],
        ),
        migrations.DeleteModel(
            name='Member',
        ),
    ]
