# Generated by Django 5.1 on 2024-12-10 02:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0006_formsubmission_delete_userprofile'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='GalleryItem',
            new_name='MemberItem',
        ),
    ]
