# Generated by Django 5.1 on 2024-12-10 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0008_gallery_galleryitem'),
    ]

    operations = [
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('serial_number', models.IntegerField()),
                ('name', models.CharField(max_length=100)),
                ('membership_number', models.CharField(max_length=50)),
                ('full_name', models.CharField(max_length=200)),
            ],
        ),
    ]
