# Generated by Django 5.1 on 2024-12-10 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0009_member'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='member',
            name='full_name',
        ),
        migrations.AlterField(
            model_name='member',
            name='membership_number',
            field=models.CharField(max_length=100),
        ),
    ]
